app = "portainer-ts-fly"
primary_region = "fra"
kill_signal = "SIGINT"
kill_timeout = 10

[[restart]]
  policy = "always"

[[vm]]
  size = "shared-cpu-1x"

[deploy]
  strategy = "immediate"

[mounts]
  source = "portainer_data"
  destination = "/data"
