# fly.toml app configuration file generated for portainer-ts-fly on 2026-03-07T20:10:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portainer-ts-fly'
primary_region = 'fra'
kill_signal = "SIGINT"
kill_timeout = 10

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[restart]]
  policy = "always"

[deploy]
  strategy = "immediate"

[mounts]
  source = "portainer_data"
  destination = "/data"
